### ISSUE TITLE
Add controls

### ISSUE THREAD

**Issue by wm-simon** [jezzdk/statamic-google-maps#1]
Hey, could you add the possibility to show the controls please? This would be really nice!

**Comment by jezzdk** [comment]
@wm-simon Sure! Fixed in v1.1.0. You can find the toggle in the settings for the fieldtype.

**Comment by wm-simon** [comment]
Hey, thank you. After the update it shows this error:
`Undefined array key "showControls"`

Statamic 3.2.32 Pro
Laravel 8.81.0
PHP 8.0.12
jezzdk/statamic-google-maps 1.1.0

**Comment by jezzdk** [comment]
@wm-simon Fixed in latest release

**Comment by wm-simon** [comment]
Works now, thank you!
