### ISSUE TITLE
Marker coordinates not saved after geocoder search

### ISSUE THREAD

**Issue by berntjs** [jezzdk/statamic-google-maps#11]
After searching for an address using the geocoder the marker is placed on the map in the control panel. Save the page, reload the editor and the marker is gone.
Now I have to manually click the map for the marker to be placed / saved.

After a geocoder search:
![1](https://github.com/jezzdk/statamic-google-maps/assets/40197443/4942c83c-36ad-49b3-bb81-9646707f823b)

After saving and reloading:
![2](https://github.com/jezzdk/statamic-google-maps/assets/40197443/b462533a-c44c-4fa7-85df-f2b912a33b00)

**Comment by jezzdk** [comment]
This has been fixed in the latest version (v2.1.0). Sorry for the long wait.
