### ISSUE TITLE
Bug: Find my location button incorrectly sized in Firefox

### ISSUE THREAD

**Issue by JameshEvoluted** [jezzdk/statamic-google-maps#2]
The icon for the "Find my location" button on the map in the control panel is incorrectly sized and covers a large portion of the map. This is occurring in Firefox but not in Chrome.

Chrome:
![Screenshot 2021-10-25 at 12 00 31](https://user-images.githubusercontent.com/25075702/138684016-b6ce2189-7ca2-4fee-b48d-9230e06a32c1.png)

Firefox:
![Screenshot 2021-10-25 at 11 52 49](https://user-images.githubusercontent.com/25075702/138683745-2547a7f1-a06b-4726-9fff-46eb9a2db15e.png)

**Comment by mnlmaier** [comment]
@jezzdk +1 happening for me aswell. basically, width and height are missing on the respective button when rendered in firefox. should be an easy fix which would be greatly appreciated :)

**Comment by jezzdk** [comment]
@JameshEvoluted @mnlmaier That is indeed an icon that is too damn big. I will fix it!

**Comment by jezzdk** [comment]
Fixed in v1.0.2
