### ISSUE TITLE
It doesn't work if configuration is cached

### ISSUE THREAD

**Issue by grandpalacko** [jezzdk/statamic-google-maps#3]
The addon uses the `env()` function in files other than config files. If the `config:cache` command is used, the `env()` function call returns `null` so the map never loads correctly.

From Laravel documentation:
"If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files. Once the configuration has been cached, the .env file will not be loaded and all calls to the env function will return null."

**Comment by mnlmaier** [comment]
+1 for me, following this issue :)
